version: "3"
services:
  proxy:
    image: nginx:latest # this will use the latest version
    ports:
      - "8080:80" # expose 8080 on host and sent to 80 in container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro #read only
  web:
    image: httpd  # this will use httpd:latest
