sudo: required
services:
  - docker

before_script: cd compose-react

before_install:
  - docker build -t anggadarkprince/docker-react -f Dockerfile.dev .

script:
  - docker run anggadarkprince/docker-react npm run test -- --coverage
