version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/codeigniter
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    
    php:
        image: php:fpm
        volumes:
            - ./:/var/www/codeigniter
        networks:
            - code-network
    
    db:
        image: mysql
        ports:
            - 33060:3306
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_DATABASE=mydb
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
